package ui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author waldo
 */
import ui.panels.MaterialsPnl;
import ui.panels.DashboardPnl;
import java.awt.CardLayout;
import ui.panels.CleanersPnl;
import ui.panels.ReportsPnl;
import ui.panels.StockIssuancePnl;
import ui.panels.SuppliersPnl;

import utils.CurrentUser;
import model.User;

public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    //This method is used to get a dim overly effect for the pop ups
    public void showDimOverlay(boolean show) {
       if (show) {
           javax.swing.JPanel glass = new javax.swing.JPanel() {
               @Override
               protected void paintComponent(java.awt.Graphics g) {
                   g.setColor(new java.awt.Color(0, 0, 0, 100)); // black, semi-transparent
                   g.fillRect(0, 0, getWidth(), getHeight());
               }
           };
           glass.setOpaque(false);
           setGlassPane(glass);
           glass.setVisible(true);
       } else {
           getGlassPane().setVisible(false);
       }
    }
    
    //This method is used to get the active highlighted effect of when a page is selected
    private void highlightSelected(javax.swing.JButton selected) {
        javax.swing.JButton[] all = {btnDashboard,btnMaterials,btnSuppliers,btnCleaners,btnStockIssuance,btnReports}; 
        for (javax.swing.JButton b : all) {
            b.setContentAreaFilled(false);
            b.setForeground(java.awt.Color.decode("#4B5563"));
            b.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        }
        selected.setContentAreaFilled(true);
        selected.setBackground(java.awt.Color.decode("#E8EFFE"));
        selected.setForeground(java.awt.Color.decode("#3B5BDB"));
        selected.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
    }
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        setResizable(false);
        setSize(1200, 700);           // fixed window size
        setLocationRelativeTo(null);  // centers it on screen
        
        //Add all the created conent panel sections
        contentPanel.add(new javax.swing.JPanel(), "Blank"); // A blank place holder will show first. As not all the users have access to all the same pages.
        contentPanel.add(new CleanersPnl(), "Cleaners");
        contentPanel.add(new DashboardPnl(), "Dashboard");
        contentPanel.add(new MaterialsPnl(), "Materials");
        contentPanel.add(new ReportsPnl(), "Reports");
        contentPanel.add(new StockIssuancePnl(), "StockIssuance");
        contentPanel.add(new SuppliersPnl(), "Suppliers");
        
        // Username and Role lables info retrieved from current logged in user info
        User currentUser = CurrentUser.get();
        if (currentUser != null) {
            lblUsername.setText(currentUser.getUsername());
            lblRole.setText(currentUser.getRole());
        }
        
        // Based on the logged in user Role some navigation buttons will not appear
        applyRoleBasedNavigation();
        
         CardLayout cl = (CardLayout) contentPanel.getLayout();
         cl.show(contentPanel, "Blank"); // shows nothing until a sidebar button is clicked
 
    }
    
    /**
    * Hides sidebar navigation buttons the current user's role
    * has no access to at all, based on the access matrix.
    */
   private void applyRoleBasedNavigation() {
       if (CurrentUser.isCleaner()) {
           // Cleaner only has access to MaterialsPnl and StockIssuancePnl, so the rest of the options are disabled.
           btnSuppliers.setVisible(false);
           btnCleaners.setVisible(false);
           btnReports.setVisible(false);
           btnDashboard.setVisible(false);
           
           btnSuppliers.setEnabled(false);
           btnCleaners.setEnabled(false);
           btnReports.setEnabled(false);
           btnDashboard.setEnabled(false);
       }
       
       // Both Owner and Storekeeper has access to page but it changes based on sepsific CRUD operations and this is changed on each page
       // See each spererate PNL for this info
       
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarPanel = new javax.swing.JPanel();
        TopLogoPnl = new javax.swing.JPanel();
        lblLogoName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        NavPnl = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnMaterials = new javax.swing.JButton();
        btnSuppliers = new javax.swing.JButton();
        btnCleaners = new javax.swing.JButton();
        btnStockIssuance = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        UserInfoPnl = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 700));
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setPreferredSize(new java.awt.Dimension(1200, 700));

        sidebarPanel.setPreferredSize(new java.awt.Dimension(200, 700));
        sidebarPanel.setLayout(new java.awt.BorderLayout());

        TopLogoPnl.setBackground(new java.awt.Color(59, 91, 219));
        TopLogoPnl.setMaximumSize(new java.awt.Dimension(200, 80));
        TopLogoPnl.setMinimumSize(new java.awt.Dimension(200, 80));
        TopLogoPnl.setPreferredSize(new java.awt.Dimension(200, 80));
        TopLogoPnl.setLayout(null);

        lblLogoName.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        lblLogoName.setForeground(new java.awt.Color(255, 255, 255));
        lblLogoName.setText("Sparkling Clean");
        TopLogoPnl.add(lblLogoName);
        lblLogoName.setBounds(20, 10, 150, 23);

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Inventory Manger of your dreams");
        TopLogoPnl.add(jLabel1);
        jLabel1.setBounds(10, 30, 190, 20);

        sidebarPanel.add(TopLogoPnl, java.awt.BorderLayout.NORTH);

        NavPnl.setBackground(new java.awt.Color(255, 255, 255));
        NavPnl.setLayout(new javax.swing.BoxLayout(NavPnl, javax.swing.BoxLayout.Y_AXIS));

        btnDashboard.setBackground(new java.awt.Color(59, 91, 219));
        btnDashboard.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(75, 85, 99));
        btnDashboard.setText("Dashboard");
        btnDashboard.setBorderPainted(false);
        btnDashboard.setContentAreaFilled(false);
        btnDashboard.setFocusPainted(false);
        btnDashboard.setMaximumSize(new java.awt.Dimension(200, 40));
        btnDashboard.setMinimumSize(new java.awt.Dimension(200, 40));
        btnDashboard.setPreferredSize(new java.awt.Dimension(200, 40));
        btnDashboard.addActionListener(this::btnDashboardActionPerformed);
        NavPnl.add(btnDashboard);

        btnMaterials.setBackground(new java.awt.Color(59, 91, 219));
        btnMaterials.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMaterials.setForeground(new java.awt.Color(75, 85, 99));
        btnMaterials.setText("Materials");
        btnMaterials.setBorderPainted(false);
        btnMaterials.setContentAreaFilled(false);
        btnMaterials.setFocusPainted(false);
        btnMaterials.setMaximumSize(new java.awt.Dimension(200, 40));
        btnMaterials.setMinimumSize(new java.awt.Dimension(200, 40));
        btnMaterials.setPreferredSize(new java.awt.Dimension(200, 40));
        btnMaterials.addActionListener(this::btnMaterialsActionPerformed);
        NavPnl.add(btnMaterials);

        btnSuppliers.setBackground(new java.awt.Color(59, 91, 219));
        btnSuppliers.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSuppliers.setForeground(new java.awt.Color(75, 85, 99));
        btnSuppliers.setText("Suppliers");
        btnSuppliers.setBorderPainted(false);
        btnSuppliers.setContentAreaFilled(false);
        btnSuppliers.setFocusPainted(false);
        btnSuppliers.setMaximumSize(new java.awt.Dimension(200, 40));
        btnSuppliers.setMinimumSize(new java.awt.Dimension(200, 40));
        btnSuppliers.setPreferredSize(new java.awt.Dimension(200, 40));
        btnSuppliers.addActionListener(this::btnSuppliersActionPerformed);
        NavPnl.add(btnSuppliers);

        btnCleaners.setBackground(new java.awt.Color(59, 91, 219));
        btnCleaners.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCleaners.setForeground(new java.awt.Color(75, 85, 99));
        btnCleaners.setText("Cleaners");
        btnCleaners.setBorderPainted(false);
        btnCleaners.setContentAreaFilled(false);
        btnCleaners.setFocusPainted(false);
        btnCleaners.setMaximumSize(new java.awt.Dimension(200, 40));
        btnCleaners.setMinimumSize(new java.awt.Dimension(200, 40));
        btnCleaners.setPreferredSize(new java.awt.Dimension(200, 40));
        btnCleaners.addActionListener(this::btnCleanersActionPerformed);
        NavPnl.add(btnCleaners);

        btnStockIssuance.setBackground(new java.awt.Color(59, 91, 219));
        btnStockIssuance.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnStockIssuance.setForeground(new java.awt.Color(75, 85, 99));
        btnStockIssuance.setText("Stock Issuance");
        btnStockIssuance.setBorderPainted(false);
        btnStockIssuance.setContentAreaFilled(false);
        btnStockIssuance.setFocusPainted(false);
        btnStockIssuance.setMaximumSize(new java.awt.Dimension(200, 40));
        btnStockIssuance.setMinimumSize(new java.awt.Dimension(200, 40));
        btnStockIssuance.setPreferredSize(new java.awt.Dimension(200, 40));
        btnStockIssuance.addActionListener(this::btnStockIssuanceActionPerformed);
        NavPnl.add(btnStockIssuance);

        btnReports.setBackground(new java.awt.Color(59, 91, 219));
        btnReports.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReports.setForeground(new java.awt.Color(75, 85, 99));
        btnReports.setText("Reports");
        btnReports.setBorderPainted(false);
        btnReports.setContentAreaFilled(false);
        btnReports.setFocusPainted(false);
        btnReports.setMaximumSize(new java.awt.Dimension(200, 40));
        btnReports.setMinimumSize(new java.awt.Dimension(200, 40));
        btnReports.setPreferredSize(new java.awt.Dimension(200, 40));
        btnReports.addActionListener(this::btnReportsActionPerformed);
        NavPnl.add(btnReports);

        sidebarPanel.add(NavPnl, java.awt.BorderLayout.CENTER);

        UserInfoPnl.setBackground(new java.awt.Color(59, 91, 219));
        UserInfoPnl.setPreferredSize(new java.awt.Dimension(70, 70));
        UserInfoPnl.setLayout(null);

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username");
        UserInfoPnl.add(lblUsername);
        lblUsername.setBounds(10, 0, 180, 20);

        lblRole.setForeground(new java.awt.Color(204, 204, 204));
        lblRole.setText("Role");
        UserInfoPnl.add(lblRole);
        lblRole.setBounds(10, 20, 170, 16);

        btnLogout.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(107, 114, 128));
        btnLogout.setText("Log out");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);
        UserInfoPnl.add(btnLogout);
        btnLogout.setBounds(80, 40, 110, 23);

        sidebarPanel.add(UserInfoPnl, java.awt.BorderLayout.SOUTH);

        getContentPane().add(sidebarPanel, java.awt.BorderLayout.LINE_START);

        contentPanel.setBackground(new java.awt.Color(245, 246, 250));
        contentPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        contentPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(contentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppliersActionPerformed
       CardLayout cl = (CardLayout) contentPanel.getLayout();
       cl.show(contentPanel, "Suppliers");   
       
        highlightSelected(btnSuppliers); // Make the button have a active effect
       
       
    }//GEN-LAST:event_btnSuppliersActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
       CardLayout cl = (CardLayout) contentPanel.getLayout();
       cl.show(contentPanel, "Dashboard");  
       
       highlightSelected(btnDashboard); // Make the button have a active effect
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnMaterialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaterialsActionPerformed
       CardLayout cl = (CardLayout) contentPanel.getLayout();
       cl.show(contentPanel, "Materials"); 
       
      highlightSelected(btnMaterials); // Make the button have a active effect
       
    }//GEN-LAST:event_btnMaterialsActionPerformed

    private void btnCleanersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanersActionPerformed
       CardLayout cl = (CardLayout) contentPanel.getLayout();
       cl.show(contentPanel, "Cleaners"); 
       
        highlightSelected(btnCleaners); // Make the button have a active effect
    }//GEN-LAST:event_btnCleanersActionPerformed

    private void btnStockIssuanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockIssuanceActionPerformed
       CardLayout cl = (CardLayout) contentPanel.getLayout();
       cl.show(contentPanel, "StockIssuance"); 
       
        highlightSelected(btnStockIssuance); // Make the button have a active effect
    }//GEN-LAST:event_btnStockIssuanceActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
       CardLayout cl = (CardLayout) contentPanel.getLayout();
       cl.show(contentPanel, "Reports"); 
       
        highlightSelected(btnReports); // Make the button have a active effect
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed

        CurrentUser.clear();   // Clear the logged in user
        this.dispose();          // Close MainFrame
        new LoginFrame().setVisible(true); // Return to the login screen
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //Change the Theme of the app
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NavPnl;
    private javax.swing.JPanel TopLogoPnl;
    private javax.swing.JPanel UserInfoPnl;
    private javax.swing.JButton btnCleaners;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMaterials;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnStockIssuance;
    private javax.swing.JButton btnSuppliers;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblLogoName;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel sidebarPanel;
    // End of variables declaration//GEN-END:variables
}
