package ui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author waldo
 */
import ui.panels.MaterialsPanel;
import ui.panels.DashboardPanel;
import java.awt.CardLayout;
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
    contentPanel.add(new DashboardPanel(), "DASHBOARD");
    contentPanel.add(new MaterialsPanel(), "MATERIALS");
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarPanel = new javax.swing.JPanel();
        dashboardbtn = new javax.swing.JButton();
        matterialsbtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidebarPanel.setPreferredSize(new java.awt.Dimension(200, 700));
        sidebarPanel.setLayout(new javax.swing.BoxLayout(sidebarPanel, javax.swing.BoxLayout.Y_AXIS));

        dashboardbtn.setText("dashboard");
        dashboardbtn.addActionListener(this::dashboardbtnActionPerformed);
        sidebarPanel.add(dashboardbtn);

        matterialsbtn.setText("mats");
        matterialsbtn.addActionListener(this::matterialsbtnActionPerformed);
        sidebarPanel.add(matterialsbtn);

        jButton3.setText("jButton3");
        sidebarPanel.add(jButton3);

        getContentPane().add(sidebarPanel, java.awt.BorderLayout.LINE_START);

        contentPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(contentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardbtnActionPerformed
       CardLayout cl = (CardLayout) contentPanel.getLayout();
       cl.show(contentPanel, "DASHBOARD");       
    }//GEN-LAST:event_dashboardbtnActionPerformed

    private void matterialsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matterialsbtnActionPerformed
       CardLayout cl = (CardLayout) contentPanel.getLayout();
       cl.show(contentPanel, "MATERIALS"); 
    }//GEN-LAST:event_matterialsbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton dashboardbtn;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton matterialsbtn;
    private javax.swing.JPanel sidebarPanel;
    // End of variables declaration//GEN-END:variables
}
